# Generated by Django 5.2.17 on 2026-09-03 23:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('claim_text', models.TextField(verbose_name='متن ادعا')),
                ('scope', models.CharField(blank=True, max_length=255, verbose_name='دامنه یا زمینه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims_created', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
            ],
            options={
                'verbose_name': 'ادعا',
                'verbose_name_plural': 'ادعاها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChangeCondition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(verbose_name='شرح شرط')),
                ('evidence_required', models.TextField(blank=True, verbose_name='شاهد موردنیاز')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20, verbose_name='شدت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_conditions', to='evidence.claim', verbose_name='ادعا')),
            ],
            options={
                'verbose_name': 'شرط تغییر',
                'verbose_name_plural': 'شرایط تغییر',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='محتوای شاهد')),
                ('content_type', models.CharField(choices=[('text', 'Text'), ('url', 'URL'), ('file', 'File'), ('image', 'Image'), ('data', 'Data'), ('other', 'Other')], default='text', max_length=50, verbose_name='نوع محتوا')),
                ('observed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان مشاهده')),
                ('integrity_digest', models.CharField(help_text='SHA-256 digest of canonical Evidence content.', max_length=64, verbose_name='هش یکپارچگی')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='فراداده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_created', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
            ],
            options={
                'verbose_name': 'شاهد',
                'verbose_name_plural': 'شواهد',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ConditionObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('observed_state', models.CharField(choices=[('unknown', 'Unknown'), ('not_observed', 'Not Observed'), ('possibly_met', 'Possibly Met'), ('met', 'Met'), ('disputed', 'Disputed')], default='unknown', max_length=20, verbose_name='وضعیت مشاهده\u200cشده')),
                ('observer_actor', models.CharField(max_length=255, verbose_name='عامل مشاهده\u200cگر')),
                ('observed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان مشاهده')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='evidence.changecondition', verbose_name='شرط')),
                ('evidence_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='condition_observations', to='evidence.evidence', verbose_name='شاهد مرتبط')),
            ],
            options={
                'verbose_name': 'مشاهده شرط',
                'verbose_name_plural': 'مشاهدات شرایط',
                'ordering': ['-observed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('retired_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان بازنشستگی')),
                ('relation', models.CharField(choices=[('supports', 'Supports'), ('contradicts', 'Contradicts'), ('contextualizes', 'Contextualizes'), ('unclear', 'Unclear')], max_length=20, verbose_name='نوع رابطه')),
                ('relation_basis', models.TextField(blank=True, verbose_name='مبنای رابطه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relations', to='evidence.claim', verbose_name='ادعا')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_relations_created', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relations', to='evidence.evidence', verbose_name='شاهد')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='evidence.evidencerelation', verbose_name='رابطه قبلی')),
            ],
            options={
                'verbose_name': 'رابطه شاهد و ادعا',
                'verbose_name_plural': 'روابط شاهد و ادعا',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProvenanceStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('human', 'Human'), ('system', 'System'), ('document', 'Document'), ('sensor', 'Sensor'), ('algorithm', 'Algorithm')], max_length=20, verbose_name='نوع منبع')),
                ('source_ref', models.CharField(max_length=255, verbose_name='ارجاع منبع')),
                ('transformation', models.CharField(blank=True, max_length=255, verbose_name='تبدیل')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان')),
                ('note', models.TextField(blank=True, verbose_name='یادداشت')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provenance_chain', to='evidence.evidence', verbose_name='شاهد')),
            ],
            options={
                'verbose_name': 'گام منشأ',
                'verbose_name_plural': 'گام\u200cهای منشأ',
                'ordering': ['timestamp', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReviewRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.CharField(max_length=255, verbose_name='شناسه موجودیت')),
                ('reviewer_actor', models.CharField(max_length=255, verbose_name='عامل بازنگری')),
                ('previous_state', models.CharField(blank=True, max_length=100, verbose_name='وضعیت قبلی')),
                ('new_state', models.CharField(max_length=100, verbose_name='وضعیت جدید')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان بازنگری')),
                ('change_conditions_met', models.JSONField(blank=True, default=list, verbose_name='شرایط تغییر مرتبط')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_review_records', to='contenttypes.contenttype', verbose_name='نوع موجودیت')),
            ],
            options={
                'verbose_name': 'رکورد بازنگری',
                'verbose_name_plural': 'رکوردهای بازنگری',
                'ordering': ['-timestamp', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentSnapshot',
            fields=[
                ('claim', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='assessment_snapshot', serialize=False, to='evidence.claim', verbose_name='ادعا')),
                ('current_assessment', models.CharField(max_length=100, verbose_name='ارزیابی جاری')),
                ('snapshot_at', models.DateTimeField(verbose_name='زمان Snapshot')),
                ('digest', models.CharField(max_length=64, verbose_name='هش Snapshot')),
                ('digest_version', models.CharField(default='v1', max_length=10, verbose_name='نسخه هش')),
                ('derived_from', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='derived_assessment_snapshots', to='evidence.reviewrecord', verbose_name='رکورد مبنا')),
            ],
            options={
                'verbose_name': 'Snapshot ارزیابی',
                'verbose_name_plural': 'Snapshotهای ارزیابی',
            },
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['content_type'], name='evidence_content_type_idx'),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['observed_at'], name='evidence_observed_at_idx'),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['integrity_digest'], name='evidence_digest_idx'),
        ),
        migrations.AddIndex(
            model_name='evidencerelation',
            index=models.Index(fields=['claim', 'evidence'], name='evrel_claim_evidence_idx'),
        ),
        migrations.AddIndex(
            model_name='evidencerelation',
            index=models.Index(fields=['retired_at'], name='evrel_retired_at_idx'),
        ),
        migrations.AddConstraint(
            model_name='evidencerelation',
            constraint=models.UniqueConstraint(condition=models.Q(('retired_at__isnull', True)), fields=('claim', 'evidence'), name='evrel_one_active_per_pair'),
        ),
        migrations.AddIndex(
            model_name='provenancestep',
            index=models.Index(fields=['evidence', 'timestamp'], name='prov_evidence_time_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewrecord',
            index=models.Index(fields=['content_type', 'object_id', '-timestamp', '-id'], name='evidence_review_target_idx'),
        ),
    ]
