# Generated by Django 5.2.17 on 2026-09-02 15:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('changes', 'Changes requested')], max_length=20, verbose_name='Decision')),
                ('notes', models.TextField(blank=True, verbose_name='Review notes')),
                ('quality_score', models.PositiveSmallIntegerField(blank=True, help_text='Optional score from 1 to 10', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Quality score')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True, verbose_name='Reviewed at')),
            ],
            options={
                'verbose_name': 'Product review',
                'verbose_name_plural': 'Product reviews',
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-published_at', '-created_at'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='product',
            name='digital_file',
            field=models.FileField(blank=True, help_text='Protected product file. Do not expose digital_file.url in public templates.', null=True, upload_to='products/files/', verbose_name='Digital file'),
        ),
        migrations.AddField(
            model_name='product',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Published at'),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags', max_length=250, verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='product',
            name='version',
            field=models.CharField(blank=True, max_length=30, verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ebook', 'E-book'), ('course', 'Course'), ('audio', 'Audio product'), ('software', 'Software'), ('template', 'Template'), ('artwork', 'Artwork'), ('other', 'Other')], default='other', max_length=30, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Full description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/images/', verbose_name='Product image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False, help_text='The product is publicly visible only when it is both approved and published.', verbose_name='Published'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_products', to=settings.AUTH_USER_MODEL, verbose_name='Seller'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.TextField(blank=True, verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=250, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20, verbose_name='Review status'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', 'is_published'], name='market_status_pub_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['seller', 'status'], name='market_seller_stat_idx'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='moderator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Moderator'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='marketplace.product', verbose_name='Product'),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['product', 'reviewed_at'], name='market_review_prod_idx'),
        ),
    ]
