# Generated by Django 5.x for VORNEQ registry foundation.

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0005_contextual_scoring_policy"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Artifact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("product", "Product"),
                            ("library_item", "Library item"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=40,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["created_at", "id"]},
        ),
        migrations.CreateModel(
            name="Identity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("human", "Human"),
                            ("organization", "Organization"),
                            ("agent", "AI agent"),
                            ("system", "System/service"),
                        ],
                        max_length=30,
                    ),
                ),
                ("display_name", models.CharField(max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["display_name", "id"]},
        ),
        migrations.CreateModel(
            name="UserIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "identity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_binding",
                        to="core.identity",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="identity_binding",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ArtifactBinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "artifact",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="binding",
                        to="core.artifact",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="core_artifact_bindings",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="artifact_bindings_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ArtifactIdentityRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("author", "Author"),
                            ("seller", "Seller"),
                            ("creator", "Creator"),
                            ("publisher", "Publisher"),
                            ("owner", "Owner"),
                            ("contributor", "Contributor"),
                        ],
                        max_length=30,
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("valid_from", models.DateTimeField(default=django.utils.timezone.now)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "artifact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="identity_roles",
                        to="core.artifact",
                    ),
                ),
                (
                    "identity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="artifact_roles",
                        to="core.identity",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="artifact",
            index=models.Index(
                fields=["kind", "is_active"],
                name="core_art_kind_active_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="identity",
            index=models.Index(
                fields=["kind", "is_active"],
                name="core_identity_kind_active_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="artifactbinding",
            constraint=models.UniqueConstraint(
                fields=("content_type", "object_id"),
                name="core_art_binding_target_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="artifactbinding",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="core_art_binding_target_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="artifactidentityrole",
            constraint=models.UniqueConstraint(
                fields=("artifact", "identity", "role"),
                name="core_art_identity_role_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="artifactidentityrole",
            index=models.Index(
                fields=["artifact", "role"],
                name="core_art_role_artifact_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="artifactidentityrole",
            index=models.Index(
                fields=["identity", "role"],
                name="core_art_role_identity_idx",
            ),
        ),
    ]
