# Generated by Django 5.2.17 on 2026-09-10 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_artifact_document_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityHandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.SlugField(max_length=32, unique=True)),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handles', to='core.identity')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('identity',), name='uniq_handle_per_identity_v1')],
            },
        ),
    ]
