# Generated by Django 5.2.17 on 2026-09-07

import uuid

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("schema_version", models.PositiveSmallIntegerField(default=1, editable=False)),
                ("event_name", models.CharField(db_index=True, max_length=100)),
                ("actor", models.JSONField()),
                ("target", models.JSONField()),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("changed", "Changed"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("granted", "Granted"),
                            ("denied", "Denied"),
                            ("revoked", "Revoked"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reason_code", models.CharField(blank=True, max_length=50)),
                (
                    "correlation_id",
                    models.CharField(blank=True, db_index=True, max_length=128, null=True),
                ),
                ("metadata", models.JSONField(default=dict)),
                (
                    "retention_class",
                    models.CharField(
                        choices=[("standard", "Standard"), ("security", "Security")],
                        default="standard",
                        max_length=20,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["event_name", "timestamp"],
                        name="audit_event_name_time_idx",
                    )
                ],
            },
        ),
    ]
